# Generated by Django 4.0.6 on 2022-07-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsSiteApp', '0004_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
